binary_sensor: 
  - platform: mqtt
    name: "Main door sensor"
    state_topic: "home/sensor/door_1/state"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: door
    qos: 1

sensor:
  - platform: mqtt
    name: "Main door sensor battery"
    state_topic: "home/sensor/door_1/battery"
    unit_of_measurement: "%"
    icon: mdi:battery